In [6]:
# Test mlflow

import mlflow

mlflow.set_tracking_uri("http://ec2-51-20-2-28.eu-north-1.compute.amazonaws.com:5000/")

with mlflow.start_run():
    mlflow.log_param("param1", 17)
    mlflow.log_metric("metric1", 0.89)

🏃 View run magnificent-ray-300 at: http://ec2-51-20-2-28.eu-north-1.compute.amazonaws.com:5000/#/experiments/0/runs/7fccbc5b03194fb982d9a7790c673c68
🧪 View experiment at: http://ec2-51-20-2-28.eu-north-1.compute.amazonaws.com:5000/#/experiments/0

In [30]:
import pandas as pd
df = pd.read_csv("processed_data.csv")

In [31]:
df.head()

,clean_comment,category,word_count,num_stop_words,num_chars,num_punctuation_chars
0,family mormon never tried explain still stare ...,1,39,13,259,0
1,buddhism much lot compatible christianity espe...,1,196,59,1268,0
2,seriously say thing first get complex explain ...,-1,86,40,459,0
3,learned want teach different focus goal not wr...,0,29,15,167,0
4,benefit may want read living buddha living chr...,1,112,45,690,0

In [33]:
df = df[['clean_comment', 'category']]
df.head()

                                       clean_comment  category
0  family mormon never tried explain still stare ...         1
1  buddhism much lot compatible christianity espe...         1
2  seriously say thing first get complex explain ...        -1
3  learned want teach different focus goal not wr...         0
4  benefit may want read living buddha living chr...         1

In [32]:
df['clean_comment'] = df['clean_comment'].fillna('')

In [34]:
import mlflow
import mlflow.sklearn
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.model_selection import train_test_split, cross_val_predict, StratifiedKFold
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [35]:
#Vectorize the comments using Bag of Words (CountVectorizer)
vectorizer = CountVectorizer(max_features=10000)  # Bag of Words model with a limit of 1000 features

X = vectorizer.fit_transform(df['clean_comment']).toarray()
y = df['category']  # Assuming 'sentiment' is the target variable (0 or 1 for binary classification)

In [36]:
X.shape

(36794, 10000)

In [37]:
y

0        1
1        1
2       -1
3        0
4        1
        ..
36789    0
36790    1
36791    0
36792    1
36793    0
Name: category, Length: 36794, dtype: int64

In [38]:
mlflow.set_tracking_uri("http://ec2-51-20-2-28.eu-north-1.compute.amazonaws.com:5000/")

In [39]:
mlflow.set_experiment("RF Baseline")

2026/03/13 05:49:14 INFO mlflow.tracking.fluent: Experiment with name 'RF Baseline' does not exist. Creating a new experiment.

In [ ]:
!aws configure

AWS Access Key ID [None]: